name: 'Update JIRA Issue'
description: 'Extract jira issue ID from branch name and updates the associated issue'
inputs:
  git-ref:
    description: 'Git reference (variable with the branch name)'
    required: true
    default: ''
  jira-base-url:  
    description: 'JIRA base URL like https://the-ring-io.atlassian.net/'
    required: false
    default: 'https://the-ring-io.atlassian.net/'
  jira-user-email:  
    description: 'JIRA user email associated with the jira token'
    required: true
    default: ''
  jira-api-token:  
    description: 'JIRA API token associated with the user email'
    required: true
    default: ''
  jira-status:  
    description: 'New JIRA status'
    required: true
    default: 'Dev in progress'
outputs:
  issue-id:
    description: "ID of the JIRA issue that was updated"
    value: ${{ steps.extract_jira_id.outputs.id }}
runs:
  using: "composite"
  steps:
    # Extract current branch name
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${{ inputs.git-ref }})" >> $GITHUB_OUTPUT
      id: extract_branch

    # Authenticate onto JIRA
    - uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-user-email }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}
    
    # Extracts the JIRA issue number from the branch name
    # The branch must math the 'XXXX/JIRA-00_MyBranchDescription' pattern
    # where XXXX is your folder like 'feat', and JIRA-00 the ID of the JIRA
    # issue you want updated
    - name: Extract JIRA issue name
      shell: bash
      id: extract_jira_id
      run: |
        jiraId=${{ steps.extract_branch.outputs.branch }}
        jiraId=${jiraId%_*}
        jiraId=${jiraId#*/}
        echo $jiraId
        echo "id=$(echo $jiraId)" >> $GITHUB_OUTPUT

    # Actually change the JIRA issue status
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.extract_jira_id.outputs.id }}
        transition: ${{ inputs.jira-status }}